platform :ios,'8.0'
target 'MVVM' do
    pod 'SDWebImage','~>3.8'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'JSONModel'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'MWPhotoBrowser'

    
end
